package com.geosid.simplephysics.ui.expirementsRegistry

import androidx.compose.runtime.Composable
import com.geosid.simplephysics.ui.experiments.week1.Day1.*
import com.geosid.simplephysics.ui.experiments.week1.Day2.*

/**
 * Single source of truth for implemented & released experiment screens across all 84 days (Weeks 1 to 12).
 */
object ExperimentScreenRegistryBackUp {
    val screens: Map<String, @Composable () -> Unit> = mapOf(
        "static_straw" to { StaticStrawExperiment() },
        "citrus_balloon" to { CitrusBalloonExperiment() },
//        "pencil_water_bag" to { PencilWaterBagExperiment() },
//        "disappearing_glass" to { RefractionGlassExperiment() },
//        "cartesian_diver" to { CartesianDiverExperiment() },
//        "oobleck" to { OobleckExperiment() },
//        "bernoulli_ball" to { BernoulliBallExperiment() },
//        "projectile_drag" to { ProjectileMotionExperiment() },
//        "bouncing_ball" to { BouncingBallExperiment() },
//        "newtons_cradle" to { NewtonsCradleExperiment() },
//        "brachistochrone" to { BrachistochroneExperiment() },
//        "terminal_velocity" to { TerminalVelocityExperiment() },
//        "stick_slip_friction" to { StickSlipFrictionExperiment() },
//        "compound_pulley" to { CompoundPulleyExperiment() },
//        "kepler_orbits" to { KeplerOrbitsExperiment() },
//        "gyroscopic_precession" to { GyroscopicPrecessionExperiment() },
//        "coriolis_effect" to { CoriolisEffectExperiment() },
//        "gravitational_slingshot" to { GravitationalSlingshotExperiment() },
//        "roche_limit" to { RocheLimitExperiment() },
//        "lagrange_points" to { LagrangePointsExperiment() },
//        "three_body_problem" to { ThreeBodyProblemExperiment() },
//        "plucked_string" to { PluckedStringExperiment() },
//        "fourier_series" to { FourierSeriesExperiment() },
//        "chladni_plates" to { ChladniPlatesExperiment() },
//        "acoustic_resonance_shatter" to { AcousticResonanceExperiment() },
//        "doppler_mach_cones" to { DopplerMachConesExperiment() },
//        "acoustic_beats" to { AcousticBeatsExperiment() },
//        "tacoma_flutter" to { TacomaFlutterExperiment() },
//        "laser_light_fountain" to { LaserFountainExperiment() },
//        "thin_film_interference" to { ThinFilmInterferenceExperiment() },
//        "youngs_double_slit" to { YoungsDoubleSlitExperiment() },
//        "prism_dispersion" to { PrismDispersionExperiment() },
//        "polarization_3_filter" to { Polarization3FilterExperiment() },
//        "diffraction_grating" to { DiffractionGratingExperiment() },
//        "atmospheric_mirage" to { AtmosphericMirageExperiment() },
//        "magnus_effect" to { MagnusEffectExperiment() },
//        "vortex_rings" to { VortexRingsExperiment() },
//        "marangoni_propulsion" to { MarangoniPropulsionExperiment() },
//        "venturi_tube" to { VenturiTubeExperiment() },
//        "hydraulic_press" to { HydraulicPressExperiment() },
//        "capillary_action" to { CapillaryActionExperiment() },
//        "karman_vortex_street" to { KarmanVortexExperiment() },
//        "ideal_gas_piston" to { IdealGasPistonExperiment() },
//        "brownian_motion" to { BrownianMotionExperiment() },
//        "leidenfrost_effect" to { LeidenfrostEffectExperiment() },
//        "stirling_engine" to { StirlingEngineExperiment() },
//        "maxwells_demon" to { MaxwellsDemonExperiment() },
//        "fourier_heat_conduction" to { FourierHeatExperiment() },
//        "blackbody_radiation" to { BlackbodyRadiationExperiment() },
//        "eddy_current_braking" to { EddyCurrentBrakingExperiment() },
//        "homopolar_motor" to { HomopolarMotorExperiment() },
//        "lorentz_cyclotron" to { LorentzCyclotronExperiment() },
//        "electromagnetic_solenoid" to { ElectromagneticSolenoidExperiment() },
//        "tesla_coil" to { TeslaCoilExperiment() },
//        "electromagnetic_railgun" to { ElectromagneticRailgunExperiment() },
//        "faraday_cage" to { FaradayCageExperiment() },
//        "double_pendulum" to { DoublePendulumExperiment() },
//        "lorenz_attractor" to { LorenzAttractorExperiment() },
//        "magnetic_chaos_pendulum" to { MagneticChaosPendulumExperiment() },
//        "conways_game_of_life" to { ConwaysGameOfLifeExperiment() },
//        "metronome_sync" to { MetronomeSyncExperiment() },
//        "sandpile_criticality" to { SandpileCriticalityExperiment() },
//        "mandelbrot_chaos" to { MandelbrotChaosExperiment() },
//        "time_dilation" to { TimeDilationExperiment() },
//        "length_contraction" to { LengthContractionExperiment() },
//        "gravitational_time_dilation" to { GravitationalTimeDilationExperiment() },
//        "black_hole_lensing" to { BlackHoleLensingExperiment() },
//        "photon_sphere_orbit" to { PhotonSphereOrbitExperiment() },
//        "gravitational_redshift" to { GravitationalRedshiftExperiment() },
//        "kerr_frame_dragging" to { KerrFrameDraggingExperiment() },
//        "photoelectric_effect" to { PhotoelectricEffectExperiment() },
//        "quantum_tunneling" to { QuantumTunnelingExperiment() },
//        "particle_in_box" to { ParticleInBoxExperiment() },
//        "heisenberg_uncertainty" to { HeisenbergUncertaintyExperiment() },
//        "quantum_harmonic_oscillator" to { QuantumHarmonicOscillatorExperiment() },
//        "stern_gerlach" to { SternGerlachExperiment() },
//        "quantum_entanglement" to { QuantumEntanglementExperiment() },
//        "stellar_fusion" to { StellarFusionExperiment() },
//        "radioactive_decay" to { RadioactiveDecayExperiment() },
//        "cherenkov_radiation" to { CherenkovRadiationExperiment() },
//        "hubble_expansion" to { HubbleExpansionExperiment() },
//        "dark_matter_rotation" to { DarkMatterRotationExperiment() },
//        "gravitational_waves" to { GravitationalWavesExperiment() },
//        "cosmic_fate" to { CosmicFateExperiment() },
    )

    fun isReleased(id: String): Boolean = screens.containsKey(id)

    fun getScreen(id: String): (@Composable () -> Unit)? = screens[id]
}
